### ISSUE TITLE
Admin view

### ISSUE THREAD

**Issue by Index01** [Index01/RoomBot#11]
Create an `/admin` view and route.
Target components;
* ability to search for a user by name & populate their owned rooms
* swap rooms between identified user and target user; include visualization of available rooms in class
* BUTTON: populate reservations (this is one time, do we need a button?)
* BUTTON: get hotel formatted diff of changes since last export
* BUTTON: get hotel formatted guest/room list
* BUTTON: sync database to master spreadsheet
* BUTTON: import current hotel state, populate "checked in"/"not checked in" & metrics

Stretch goals: 
metrics: 
 * how many available rooms within a class, grouped by floor
 * how many rooms checked in / not checked in

**Comment by Index01** [comment]
Draft PR with frontend basics demoed in last mtg
https://github.com/Index01/RoomBot/pull/34

**Comment by mpesavento** [comment]
Calling this done for now, subtickets will pick up the missing components:
* import guests file or diff file via uploaded csv
* export hotel-formatted output
* export reports
* admin permissions for manual room swaps
