### ISSUE TITLE
run.sh

### ISSUE THREAD

**Issue by Index01** [Index01/RoomBot#12]
Starting the django server and node frontend requires two separate commands. Both can run in the background, but will need some terminate signal if one is killed and the other is left alive.

Create a run.sh or something for the overall startup to make it easier to start up the application.

**Comment by otakup0pe** [comment]
i'm interpreting `something` as a systemd widget w/ auto restarts

**Comment by mpesavento** [comment]
@otakup0pe That is more than what I was expecting, and sounds amazing if not that much additional lift.
This is intended to be a quick one-command entry point to running the system, rather than a chain of commands and parameters as it currently stands.

**Comment by otakup0pe** [comment]
Adding systemd for a django thing isn't that hard. For the frontend, if we host in `nginx`, it will come for free. The work will be in the nginx config - which isn't super difficult.

**Comment by otakup0pe** [comment]
Peek ⬆️  PR - React bits are served via nginx, django bits are served via wsgi via nginx.

**Comment by mpesavento** [comment]
looks like @otakup0pe did an amazing job in creating a deployment script to add the django backend as a `systemctl` service in #35 , calling this complete!
