### ISSUE TITLE
update database to postgres/RDS

### ISSUE THREAD

**Issue by Index01** [Index01/RoomBot#13]
sqlite to postgress, using all the nice EC2 tools. 

- start to outline a plan.
- look at in memory file backup
  - saving timestamped updates. even just on a cronjob
  - add backup file generation as a first pass, before shifting to RDS
- table mgmt
  - adding production co and event id fields

**Comment by otakup0pe** [comment]
by "nice EC2 tools" does this mean RDS?

**Comment by Index01** [comment]
@otakup0pe yyyeeessss it does thank you for speaking Index!

**Comment by otakup0pe** [comment]
Peek ⬆️ - uses RDS and the deploy script handles migrations.

**Comment by mpesavento** [comment]
We still need to test the deploy on a production RDS
@otakup0pe can you connect me with the AWS credentials to be able to see whats going on the inside? currently a high bus factor there.
