### ISSUE TITLE
Double allocation problem

### ISSUE THREAD

**Issue by Index01** [Index01/RoomBot#132]
guest list updates resulting in double allocated rooms.
in staging the transfer (5XHAR) appears to complete. in prod not so much

![roombaht_bug_doubleallocateroom_staging](https://github.com/Index01/RoomBot/assets/3605312/a7eba926-4ec6-490d-b4dd-d7fc295592b6)
![roombaht_bug_doubleallocateroom_prod](https://github.com/Index01/RoomBot/assets/3605312/d762edac-d86e-4783-91c7-cd6d6826b307)

**Comment by Index01** [comment]
Looking into this now @mpesavento @otakup0pe

**Comment by Index01** [comment]
I suspect reversing the guest list will resolve the issue.
trying that now in staging but staging isnt rly seeing the problem in the same way so experiment time.

**Comment by mpesavento** [comment]
This might be fixed in #131

**Comment by otakup0pe** [comment]
even after fresh data, `find_drama` command showing nothing. considering this closed.
