### ISSUE TITLE
Create DNS routing to EC2 host

### ISSUE THREAD

**Issue by mpesavento** [Index01/RoomBot#17]
Currently, the IP address to the EC2 host is hardcoded into the code.
Let's fix this by creating a hostname and using route53 to DNS map it to an elastic IP for the Ec2 instance, so we can avoid the IP commenting issue.

**Comment by otakup0pe** [comment]
- [ ] use an env var for the hostname in the various code places
- [ ] something something manually poke route53

**Comment by Index01** [comment]
Env var sounds right for switching localhost vs EC2. 
My route53 foo is minimal if others has more exp.

**Comment by otakup0pe** [comment]
I know how to `route53` either by hand or yaml or tears.

**Comment by Index01** [comment]
Seems like this ticket and ticket #8 (https://github.com/Index01/RoomBot/issues/8) are blending together. 

I'll probably scrape the description from #8 into this ticket

**Comment by otakup0pe** [comment]
If we want the shortcut hostname on the `roomserviceparty.com` domain then it might need to be configured on squarespace. Unless we do a subdomain which feels like more trouble than worth (unless we end up wanting an actual (non-local) dev instance).

**Comment by mpesavento** [comment]
My target would be to link a host to a subdomain, like `roombaht.roomserviceparty.com`. It's a nice to have, at the least it would be good to have a static IP to point to.

**Comment by mpesavento** [comment]
@mpesavento to map IP address to DNS name `roombaht.roomserviceparty.com`

**Comment by mpesavento** [comment]
We have `http://rooms.take3presents.com` pointing to our `44.228.91.225` elastic IP address.
It looks like there is an incomplete DNS record, as only port 80 is forwarding. We need an `A` record to point to the IP address

**Comment by mpesavento** [comment]
A record created, looks like ports are forwarding.
