### ISSUE TITLE
update room csv for this year

### ISSUE THREAD

**Issue by otakup0pe** [Index01/RoomBot#182]
# definitely drop

* `room_owned_by`
* `changeable`
* `change_reason`
* `placement_team_notes`
* `room_notes`
* `paying_guest`
* `department`
* `placement_verified`
* `connected_to`
* `floor`

# probably drop

* `art_room`
* `art_room_type`
* `art_name_placed_by`
* `guest_restriction_notes`

**Comment by alvarezb** [comment]
updated sample CSVs to remove all columns listed *except* `guest_restriction_notes` and linked the branch
