### ISSUE TITLE
use argparse/yaml in populate_reservations

### ISSUE THREAD

**Issue by otakup0pe** [Index01/RoomBot#20]
Whole lotta comments and env vars in there. Should use argparse/yaml for

* email bits ( #18 ) as (shared?) yaml config
* `SEND_EMAIL` global var
* `RANDOM_ROOM` global var
* input CSV
* `type_mapping` should probably be a yaml

**Comment by mpesavento** [comment]
bunch of great fixes here! Calling this done.
