### ISSUE TITLE
Update the master table schema, and the associated room/guest schemas

### ISSUE THREAD

**Issue by mpesavento** [Index01/RoomBot#21]
In the master spreadsheet, we want to make sure the table has these additional fields:
* second contact for room, first & last name
* field for `is_swappable`
* (maybe) field for original owner of room from Secret Party data
* notes on room
* notes on guest
* smoking/non-smoking (not guest visible)
* Lakeview (not guest visible)
* accessibility (ADA, hearing accessible) (not guest visible)

Map these fields out to the associated tables for `room` and `guest`

Create an explicit schema for the export to the hotel system, and the import from the hotel system

**Comment by mpesavento** [comment]
@mpesavento still to confirm this schema is what we want moving forward.

**Comment by otakup0pe** [comment]
Can we get this confirmed so I can make the schema change(s) ?

**Comment by Index01** [comment]
I would also like `is_swappable` and would like "available" changed to `is_available` perhaps?

thx luv ur werk @otakup0pe

**Comment by otakup0pe** [comment]
Also going to add the `Ticket ID in Secret Party` (as known in the main spreadsheet)  so we can remove the dependency on the rooms dot csv during guests dot csv uploading.

**Comment by mpesavento** [comment]
Looks like this is stable, given #54 .
Are we missing any core functionality here?

**Comment by otakup0pe** [comment]
I believe this is safe to close. There are still some changes to the create/update logic that might be needed pending further testing, but the schema is solid.
