### ISSUE TITLE
Create method for exporting CSV to the hotel

### ISSUE THREAD

**Issue by mpesavento** [Index01/RoomBot#23]
The CSV required by the hotel will include
* room #
* room type
* first name
* last name
* check in date
* check out date

Previously, this data was exported from the master spreadsheet in google sheets. We want to create a method to export the most recent data from Roombaht to the hotel, and have this be accessible via a button in the /admin page

We will likely want options for both a full export and a diff from the last export. MVP will be the full export.

**Comment by otakup0pe** [comment]
Also need to include

* secondary name
