### ISSUE TITLE
frontend does nothing outside of dev mode

### ISSUE THREAD

**Issue by otakup0pe** [Index01/RoomBot#25]
Starts up but no requests to backend, nothing on console log. It might just be that I don't know How To React.

![](https://i.imgur.com/HEJgVJN.jpg)

**Comment by Index01** [comment]
Hmmm is this when u try `npm run build`??
Double check the ips in the Axios request is correct, localhost for local dev vs EC2?

**Comment by otakup0pe** [comment]
This was all `localhost`. I tried serving it via `python -m http.server -d frontend/build/`

**Comment by Index01** [comment]
Might be easier to show this on a zoom call screen share. The 1,2,3 of it though is:

1. source .env from backend and frontend. python runserver from backend, npm start from frontend. python pop_res.py script
![startup1](https://github.com/Index01/RoomBot/assets/3605312/d1b29a3c-f06c-42e6-bc1a-158636f12f06)

2. go to the /login url, copy one time pass from pop_res output. complete login, click buttons, see react/frontend logging to browser console.
![startup2](https://github.com/Index01/RoomBot/assets/3605312/2b246bdf-924b-4f1e-a9db-f1182d18a48e)

3.  see backend logging in the terminal where backend was started.
![startup3](https://github.com/Index01/RoomBot/assets/3605312/bacfa6a2-9140-4831-b2e3-b0abfca88271)

**Comment by otakup0pe** [comment]
hmm so i'm hearing it _did_ work on your machine? will poke at it a bit more.

**Comment by otakup0pe** [comment]
See ⬆️. Based on the react router used, need to do some nginx path fuckery in order for it to work, which explains why it didn't work with a plain python webserver.

**Comment by Index01** [comment]
@mpesavento @otakup0pe is this good to close or bit more?

**Comment by otakup0pe** [comment]
good to close once the pr is merged.

**Comment by mpesavento** [comment]
done! closing
