### ISSUE TITLE
Set up users that have access to admin page

### ISSUE THREAD

**Issue by mpesavento** [Index01/RoomBot#32]
We have `/admin`, which will have buttons for import/export & admin swaps.

Create the accounts to access this.
Small version: single password to access the admin page

How do we want to create the admins?

**Comment by Index01** [comment]
For branch tracking purposes maybe we consider this a sub-issue of #11 ??

I'll push the initial admin branch and link to it in that ticket. Then log this work as a first priorty task in that issue

**Comment by mpesavento** [comment]
Current solution is to have an admins table.
@Index01 We will need to find a way to export and share the passwords for a production instance

**Comment by Index01** [comment]
This should be werking from the last PR, #11 

add user to the /samples/exampleStaff.csv, mark is_admin true then run the pop_res.py script

**Comment by otakup0pe** [comment]
@Index01 can we close this?

**Comment by mpesavento** [comment]
Good enough, closing!
