### ISSUE TITLE
Data ingestion: SP & room inventory

### ISSUE THREAD

**Issue by mpesavento** [Index01/RoomBot#33]
Most of this is in populate_reservations.py
Put this on admin page:
buttons:
* import room inventory
* import SP guests

* ingest room inventory from google sheets CSV
* ingest customer room ticket information from SP CSV
* Merge two tables into one main table, populate changable rooms with guests 
* load rooms & guests table
* make backup/report

**Comment by Index01** [comment]
- ingest room inventory from google sheets CSV

Ticket #38 created as first step for the above item. Followed by #39

**Comment by Index01** [comment]
- import SP guests

Completed move to /admin page, PR open. 
Currently reading from /samples directory. That need be changed to either upload or read from drive. Latter preferred as described here issue #39

**Comment by Index01** [comment]
- import room inventory

Sounds like this will stay in pop_res.py script since we only import rooms once. As discussed in last Monday mtg.

**Comment by mpesavento** [comment]
@Index01 
Let's rename pop_reservation to something like populate_rooms, to clarify what the intended goal of the script is.

**Comment by Index01** [comment]
defffff will chat tmw

**Comment by mpesavento** [comment]
Calling this one done for now, will create a new ticket for the finesse in ticket_id logic
