### ISSUE TITLE
Gmail/GDrive auth

### ISSUE THREAD

**Issue by Index01** [Index01/RoomBot#38]
Login to the placement@take3 Gmail, create the application password(API token or Oauth or whatever they call it) to enable sending mail and accessing GDrive files. Many guides are available online for accessing Google services from Python. 

Should be a process like this: https://developers.google.com/drive/api/quickstart/python 

 Completion criteria:
- credentials, in my hand

**Comment by Index01** [comment]
better yet credentials in the encrypted env vars file, in the repo, verified working with a PR open :smile: 
A them can dream, right?

**Comment by mpesavento** [comment]
We should be able to get the API key for gmail auth, and save that in the secrets file.
We need to have this functionality tested in the next few days.

**Comment by otakup0pe** [comment]
Looks like we will need both an app password (for smtp email) and a separate API key (for the gdrive stuff).
