### ISSUE TITLE
Admin view import/export requirements

### ISSUE THREAD

**Issue by mpesavento** [Index01/RoomBot#41]
The admin view still needs a few key features:

1. import a guests CSV file, from the spreadsheet and/or from secret party. This will then load the rooms.
2. export hotel-formatted CSV for the hotel records
3. export reports

**Comment by Index01** [comment]
number 1 above needs the production csv 
number 2 and 3 need email working to send the reports

both have dev workflows(loading the /samples/example*.csv files and output in /output/), both need verified. email would be helpful in that

**Comment by mpesavento** [comment]
@Index01 we now have the production CSV, and the email working. 
Let's call this complete when we have the ability to:
* export csv to hotel (full and diff)
* export spreadsheet CSV in target schema for the main spreadsheet

**Comment by Index01** [comment]
sounds good

do we know the exact hotel format @mpesavento? If anyone can provide column headers for what they expect, and whether it should be a full export or only a diff, would be much appreciated.

**Comment by otakup0pe** [comment]
Hotel format has been verified and is in #23 

I'm going to be making some fixes in #54 to handle race conditions in the report generation that could result in diffs being mucked up or incomplete reports being emailed.

**Comment by otakup0pe** [comment]
Given the hotel export PR this is _basically_ complete. I will be taking a pass through the logic for rooms/guests to ensure they can be updated-in-place as that will give us a _ton_ of flexibility that future us will probably be happy to have. Once the hotel PR is merged we can probably close this tho as it currently does what it says on the tin.
