### ISSUE TITLE
Selected guest room display not displaying

### ISSUE THREAD

**Issue by mpesavento** [Index01/RoomBot#42]
The guest room selection displays a placeholder for the owned room numbers
It also doesn't display the room type, making it hard for the guest to know what or where their room is.
![image](https://github.com/Index01/RoomBot/assets/154588/ed846c63-6c0d-4a6f-b3bb-5199515e2b14)

@Index01 
the 666 is the RANDOM_ROOMS  env var string comparison issue

**Comment by Index01** [comment]
should be fixed here https://github.com/Index01/RoomBot/pull/44

please pull and verify on your system

**Comment by mpesavento** [comment]
Confirming fix, thank you!
