### ISSUE TITLE
Make swap code C&Pable from guest interface

### ISSUE THREAD

**Issue by mpesavento** [Index01/RoomBot#43]
When a guest clicks on the CreateSwapCode button, it creates a modal dialog:
![image](https://github.com/Index01/RoomBot/assets/154588/886d706f-49fb-465b-b218-08962f97fedf)
The swap code is not selectable, meaning that the user would have to manually retype it somewhere.

Is there a way to make this text selectable?
---
Possbile solutions

from @Index01 
I think we want to switch to something like this 
https://react-bootstrap.netlify.app/docs/components/modal
which i think allows text copy but we would probably need to test it across multiple-browsers. 
[mjp note: it should be fine across browsers, better than what we have now]

**Comment by Index01** [comment]
Aaanddd dooneee https://github.com/Index01/RoomBot/pull/45
