### ISSUE TITLE
Fix everything.

### ISSUE THREAD

**Issue by Index01** [Index01/RoomBot#5]
- [ ] Make all the bits work

**Comment by otakup0pe** [comment]
[![that was easy](https://media.tenor.com/r1eMxzMvWGQAAAAM/easy-button-that-was-easy.gif)](https://www.youtube.com/watch?v=ZXVhOPiM4mk)

**Comment by mpesavento** [comment]
Calling this issue closed, now that we have more granularity.
Yay we did a task!
