### ISSUE TITLE
Ticket swap updates using from previous ticket_id

### ISSUE THREAD

**Issue by mpesavento** [Index01/RoomBot#51]
We want to upload new guest lists that may have a new ticket_id for a given room owner.
* Start with baseline export from SecretParty, all transfers in place at that timestamp
* get updated SP list, and update any transfers in the DB from the prior ticket_id to the new ticket_id

**Comment by otakup0pe** [comment]
Is this more than just handling room transfers?

**Comment by mpesavento** [comment]
Calling this complete, room transfers are now handled with the new SP schema
