### ISSUE TITLE
Expire jwt

### ISSUE THREAD

**Issue by Index01** [Index01/RoomBot#6]
Maybe eventually fix this but turns out is a feature for now. 

https://github.com/Index01/RoomBot/blob/f49d4d7bb5a849736ab38827ddeec851618c8381/backend/reservations/views.py#L86

**Comment by mpesavento** [comment]
@Index01 Do we want to convert this issue into "fix JWT to populate guest table"?

**Comment by Index01** [comment]
@mpesavento looks like the containing function is used quite a bit in views.py so may not want to limit it to guest table. Unless u had other contexts in mind.
Looks like quick fix tho. Arithmetic flip. Happened to be a feature because I could use the same jwt for testing over several days.

**Comment by mpesavento** [comment]
Sounds good! Doesnt need to just be for guest table, that was just where i understood it to be required.

**Comment by Index01** [comment]
is fixed. 
https://github.com/Index01/RoomBot/blob/3178bbec379ee3291ed5116aac845d9a1ca11633/backend/reservations/views/rooms.py#L46

think was part of the code cleanup merge.
