### ISSUE TITLE
store both hotel name formats

### ISSUE THREAD

**Issue by otakup0pe** [Index01/RoomBot#66]
Preserve both name formats - our "short" name and the hotel "real" name (or a close approximation thereof).

* Only short name should be displayed to users
  * Admins can see both
* Include "real" name in the export

**Comment by Index01** [comment]
Hmm yea we had hoped to avoid that having one set of names for t3 and one set of names for hotel. kinda seems we are falling back to that. unless we can derive the hotel names from existing fields?

**Comment by otakup0pe** [comment]
I think we can kinda derive but the closest we can get to the "hotel name" is by using what we get from them.

Short term solution - store both in room record
Long term solution - move the `ROOM_TYPES` constant and it's friends into a separate table and then just link
