### ISSUE TITLE
Use production webserver

### ISSUE THREAD

**Issue by Index01** [Index01/RoomBot#7]
We have been using the builtin node and Django webserver. This is fine for testing but more than a few dozen concurrent requests causes them to fall over.  We experienced this issue when we went live the first time, people reported errors, I told them try again and it worked. That solution may not scale for hundreds of users. 

Completion criteria:
- use gunicorn/apache/nginx/etc for the nodeJS and/or Django server. 
- configs and user guide exist

I think I have a greenletServet/gunicorn config somewhere, it might be for kubernetes tho which is a whole other thing.

**Comment by Index01** [comment]
```
(env) t4l3r@ind3x:~/repoz/take3/RoomBot/backend$ python manage.py runserver
Watching for file changes with StatReloader
Performing system checks...

System check identified no issues (0 silenced).
September 22, 2023 - 23:38:23
Django version 4.1.1, using settings 'backend.settings'
Starting development server at http://127.0.0.1:8000/
Quit the server with CONTROL-C.

```

`Starting development server`
we want production server, not dev

**Comment by otakup0pe** [comment]
* would lean towards `nginx` (i seem to recall wsgi is easy there)
* supporting > dozenish concurrent may necessitate moving off sqlite
* assuming we'd serve static content via `nginx`

**Comment by Index01** [comment]
@otakup0pe sounds right to me. 
- replace development Web servers with nginx.
- replace sqlite with Postgres. 

Let me know how I can assist or post updates here!

**Comment by mpesavento** [comment]
Let's keep the DB update to another task, and just focus this task on upgrading the web server to an `nginx` backend.

**Comment by mpesavento** [comment]
@otakup0pe Look into frontend without using npm, point nginx to static content
django is serving through WSGI, point nginx at that
