### ISSUE TITLE
`RequestReset` button on login does not notify user that something happened

### ISSUE THREAD

**Issue by mpesavento** [Index01/RoomBot#78]
Redefining this issue to add feedback (via a toast?) to the user that password reset was successful and email was sent.

PREVIOUS ISSUE:
-----------------
The other button on the frontend /login screen is giving a "Failed to load resource" error:
```
:8080/api/login_reset/:1 
Failed to load resource: the server responded with a status of 400 (Bad Request)
```

Fix this so guests can receive a new password.

**Comment by otakup0pe** [comment]
Unclear from this issue where the problem was experienced. Was it the prod instance?

**Comment by otakup0pe** [comment]
password reset working on prod post-delpoy 🤷🏼

**Comment by mpesavento** [comment]
Okay, looks like this issue may be working as is.
There is zero notification to the user that a password reset was sent as an email. I'm going to update the task to add user feedback in GUI.

**Comment by otakup0pe** [comment]
Agree :100: that we need more feedback on both good (i.e. email sent) and bad (i.e. #62 )
