### ISSUE TITLE
Omnibus issue: To fix post RS23

### ISSUE THREAD

**Issue by mpesavento** [Index01/RoomBot#79]
Some things we want to fix for next year:
* read/write to master rooms spreadsheets
* more admin features for placement: 
   * better table viz, 
   * "airline seat assignment" view of rooms on floors
   * admin swap room in RoomBaht

**Comment by otakup0pe** [comment]
These exist as #39, #40, #163, and pretty sure we ended up tidying up the admin table ux - at least it doesn't look too bad rn
