### ISSUE TITLE
Create dynamic config for localhost vs EC2 

### ISSUE THREAD

**Issue by Index01** [Index01/RoomBot#8]
Might just be env vars. Some work exists. Production comment switches, let's not do that again. Having this work would be very helpful for new devs and local development.

Completion criteria:
- a switch exists for prod or local dev. Mostly involves setting different IPs. 
- feature is merged to main 
- there is a secure and effective way to distribute these configs(IPs, hostnames, etc). Currently this is a .env file

**Comment by Index01** [comment]
route53 possible solution?!

**Comment by otakup0pe** [comment]
Starting to lean towards yaml config files for the various configurable bits including domains, #18 and anything we aren't going to use `argparse` for in `populate_reservations.py`

**Comment by mpesavento** [comment]
I'm good with yaml configs! 
That would look like loading in some parameters at the app load, and figuring out which target host to point to (local vs ec2) via a flag?

**Comment by Index01** [comment]
I believe @otakup0pe took on the .env vars.
Can confirm functionality to switch between dev (localhost) and prod(aws)??

**Comment by otakup0pe** [comment]
decided yaml wasn't lo-fi enough. do we think it's worth it to create a set of pre-defined dev vs prod env?

**Comment by mpesavento** [comment]
This is mostly done, with production secrets stored in an encrypted file #36  and dev secrets stored in an open file #37 
Calling this issue closed.
