### ISSUE TITLE
update routes

### ISSUE THREAD

**Issue by Index01** [Index01/RoomBot#9]
Observations after not looking at this for months

Completion criteria:
- `/` should route to `/login` @otakup0pe 

- access to `/rooms` should be denied to non-authenticated users (JWT related) @Index01 
  - current behavior appears to allow access to the /rooms page and just populates no data. 
  - no auth header redirect to /login

**Comment by otakup0pe** [comment]
* `/` ➡️ `/login` redirect can be accomplished via `nginx`
* access denied or just redirect to `/login` ?

**Comment by Index01** [comment]
@otakup0pe kewl nginx level redirect sounds good. Access denied authorization bearer was my initial thought but desired effect is client without a valid jwt redirects to `/login`. If you see a clean way to do that redirect without access denied is fine by me!

**Comment by otakup0pe** [comment]
#35 addresses the `/` redirect

**Comment by Index01** [comment]
I think the `/` redirect addresses the immediate needs of this ticket. 
@mpesavento i recommend we close this ticket and create another for the /rooms redirect in the future. or change this to a P2+.  currently the /rooms route will return empty if the use is not authenticated. would be better to redicrect to /login but seems like we have higher priorities right now ja?

**Comment by otakup0pe** [comment]
fwiw i'm pretty sure we can do the `/rooms` redirect in `nginx` but was trying to get it done in js
